### PR TITLE
Add Installation instructions and a copy-pastable dependency info

### PR DESCRIPTION
**Pull request by DjebbZ**
Instructions shamelessly copied from https://github.com/jsofra/data-scope

### CODE REVIEW

**Comment by DjebbZ** [comment]
Finally started to use it. Lovin' it already :cupid: 

My thanks in a PR :wink:

**Comment by vvvvalvalval** [comment]
@DjebbZ Thanks, interesting, I did not know this trick. However, have you tested this approach for (many flavors of) ClojureScript? I need this to work for a wide variety of REPLs, and preferrably not presume that the REPL was setup via Boot or Leiningen. 

If this approach is not portable, I'd rather document it in something like a 'Tips and Tricks' section of the documentation (which would be referenced in the README).

**Comment by DjebbZ** [comment]
Well, I recommend against hiding basing instructions far from the eyes. A good README should include the basic instructions to start right away. Look at the [ClojureScript repo](https://github.com/clojure/clojurescript), [Om](https://github.com/omcljs/om), [Reagent](https://github.com/reagent-project/reagent), [Leiningen](https://github.com/technomancy/leiningen), [Ring](https://github.com/ring-clojure/ring), or even [Golang](https://github.com/golang/go) or [Rails](https://github.com/rails/rails). They all display clear and proeminent basic installation instructions.

Now, I haven't tested at all the ClojureScript part, neither a bare Clojure REPL. I understand it can be trickier and that my contrib doesn't explain these cases. But one can always add them later.

Last note : unless it's tricky, I wouldn't hide this information from the README.

Keep up the good work !

_(Note to self : contribute a Table of Content)_

**Comment by vvvvalvalval** [comment]
Fair enough, merging. I'm also working on some documentation to help people get started, so expect some changes soon :)

Thanks for helping out!

**Pull request merged**
